In [ ]:

import sqlite3
import pandas as pd

# Create an in-memory SQLite database
conn = sqlite3.connect(":memory:")
cursor = conn.cursor()

# Create a Sales table
cursor.execute("""
CREATE TABLE Sales (
    SaleID INTEGER,
    Product TEXT,
    Category TEXT,
    Amount REAL,
    Quantity INTEGER
)
""")

sales_data = [
    (1, 'Laptop', 'Electronics', 50000, 2),
    (2, 'Mouse', 'Electronics', 800, 5),
    (3, 'Keyboard', 'Electronics', 1500, 3),
    (4, 'Chair', 'Furniture', 4500, 4),
    (5, 'Desk', 'Furniture', 9000, 2),
    (6, 'Notebook', 'Stationery', 100, 10),
    (7, 'Pen', 'Stationery', 20, 20),
    (8, 'Monitor', 'Electronics', 12000, 2),
    (9, 'Table', 'Furniture', None, 1),
    (10, 'Lamp', 'Furniture', 1200, 3)
]

cursor.executemany(
    "INSERT INTO Sales VALUES (?, ?, ?, ?, ?)",
    sales_data
)
conn.commit()

print("Sales table created successfully!")
display(pd.read_sql_query("SELECT * FROM Sales", conn))

Sales table created successfully!

   SaleID   Product     Category   Amount  Quantity
0       1    Laptop  Electronics  50000.0         2
1       2     Mouse  Electronics    800.0         5
2       3  Keyboard  Electronics   1500.0         3
3       4     Chair    Furniture   4500.0         4
4       5      Desk    Furniture   9000.0         2
5       6  Notebook   Stationery    100.0        10
6       7       Pen   Stationery     20.0        20
7       8   Monitor  Electronics  12000.0         2
8       9     Table    Furniture      NaN         1
9      10      Lamp    Furniture   1200.0         3

In [ ]:
query = """
SELECT COUNT(*) AS TotalRecords
FROM Sales;
"""
display(pd.read_sql_query(query, conn))

   TotalRecords
0            10

In [ ]:
query = """
SELECT SUM(Amount) AS TotalSales
FROM Sales;
"""
display(pd.read_sql_query(query, conn))

   TotalSales
0     79120.0

In [ ]:
query = """
SELECT AVG(Amount) AS AverageSales
FROM Sales;
"""
display(pd.read_sql_query(query, conn))

   AverageSales
0   8791.111111

In [ ]:
query = """
SELECT MIN(Amount) AS MinimumSale
FROM Sales;
"""
display(pd.read_sql_query(query, conn))

   MinimumSale
0         20.0

In [ ]:
query = """
SELECT MAX(Amount) AS MaximumSale
FROM Sales;
"""
display(pd.read_sql_query(query, conn))

   MaximumSale
0      50000.0

In [ ]:
query = """
SELECT Category, COUNT(*) AS TotalRecords
FROM Sales
GROUP BY Category;
"""
display(pd.read_sql_query(query, conn))

      Category  TotalRecords
0  Electronics             4
1    Furniture             4
2   Stationery             2

In [ ]:
query = """
SELECT Category, SUM(Amount) AS CategorySales
FROM Sales
GROUP BY Category;
"""
display(pd.read_sql_query(query, conn))

      Category  CategorySales
0  Electronics        64300.0
1    Furniture        14700.0
2   Stationery          120.0

In [ ]:
query = """
SELECT Category, AVG(Amount) AS AverageSale
FROM Sales
GROUP BY Category;
"""
display(pd.read_sql_query(query, conn))

      Category  AverageSale
0  Electronics      16075.0
1    Furniture       4900.0
2   Stationery         60.0

In [ ]:
query = """
SELECT
    Category,
    MIN(Amount) AS MinimumSale,
    MAX(Amount) AS MaximumSale
FROM Sales
GROUP BY Category;
"""
display(pd.read_sql_query(query, conn))

      Category  MinimumSale  MaximumSale
0  Electronics        800.0      50000.0
1    Furniture       1200.0       9000.0
2   Stationery         20.0        100.0

In [ ]:
query = """
SELECT
    COUNT(*) AS TotalRecords,
    COUNT(Amount) AS RecordsWithAmount,
    COUNT(*) - COUNT(Amount) AS MissingAmounts
FROM Sales;
"""
display(pd.read_sql_query(query, conn))

   TotalRecords  RecordsWithAmount  MissingAmounts
0            10                  9               1